name: dbt Release
on:
  push:
    branches:
      - prod
      - test

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'test' }}
      DBT_DATABRICKS_HOST: ${{ secrets.DBT_HOST }}
      DBT_DATABRICKS_HTTP_PATH: ${{ secrets.DBT_HTTP_PATH }}
      DBT_DATABRICKS_TOKEN: ${{ secrets.DBT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dbt/dbt-deps.txt
        continue-on-error: false

      - name: dbt Seed
        run: |
          dbt seed --project-dir dbt/ --profiles-dir dbt/ --target ${{ env.TARGET }}
        continue-on-error: false

      - name: dbt Run
        run: |
          dbt run --project-dir dbt/ --profiles-dir dbt/ --target ${{ env.TARGET }}
        continue-on-error: false
